import type { Car } from "@/lib/types";

/** Shown on the public site only while Firebase is not configured (local preview). */
const base = {
  color: "",
  description: "",
  status: "available" as const,
  images: [],
  imagePaths: [],
  soldAt: null,
};

export const SAMPLE_CARS: Car[] = [
  {
    ...base,
    id: "sample-1",
    make: "Porsche",
    model: "911 Carrera S",
    bodyType: "Coupe",
    year: 2023,
    price: 142900,
    mileage: 8200,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: true,
    createdAt: 5,
  },
  {
    ...base,
    id: "sample-2",
    make: "Tesla",
    model: "Model S Plaid",
    bodyType: "Sedan",
    year: 2024,
    price: 94990,
    mileage: 3100,
    transmission: "Automatic",
    fuel: "Electric",
    featured: true,
    createdAt: 4,
  },
  {
    ...base,
    id: "sample-3",
    make: "Land Rover",
    model: "Defender 110",
    bodyType: "SUV",
    year: 2022,
    price: 71500,
    mileage: 21400,
    transmission: "Automatic",
    fuel: "Diesel",
    featured: false,
    createdAt: 3,
  },
  {
    ...base,
    id: "sample-4",
    make: "BMW",
    model: "M4 Competition",
    bodyType: "Coupe",
    year: 2023,
    price: 86400,
    mileage: 11900,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: 2,
  },
  {
    ...base,
    id: "sample-5",
    make: "Ford",
    model: "F-150 Lightning",
    bodyType: "Truck",
    year: 2023,
    price: 62800,
    mileage: 14500,
    transmission: "Automatic",
    fuel: "Electric",
    featured: false,
    createdAt: 1,
  },
  {
    ...base,
    id: "sample-6",
    make: "Mercedes-Benz",
    model: "G 550",
    bodyType: "SUV",
    year: 2021,
    price: 148000,
    mileage: 18700,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: 0,
  },
  {
    ...base,
    id: "sample-7",
    make: "Audi",
    model: "RS e-tron GT",
    bodyType: "Sedan",
    year: 2023,
    price: 129900,
    mileage: 6700,
    transmission: "Automatic",
    fuel: "Electric",
    featured: false,
    createdAt: -1,
  },
  {
    ...base,
    id: "sample-8",
    make: "Chevrolet",
    model: "Corvette Stingray",
    bodyType: "Coupe",
    year: 2022,
    price: 78900,
    mileage: 9800,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: -2,
  },
  {
    ...base,
    id: "sample-9",
    make: "Toyota",
    model: "Land Cruiser",
    bodyType: "SUV",
    year: 2024,
    price: 87500,
    mileage: 1900,
    transmission: "Automatic",
    fuel: "Hybrid",
    featured: false,
    createdAt: -3,
  },
  {
    ...base,
    id: "sample-10",
    make: "Lexus",
    model: "LC 500 Convertible",
    bodyType: "Convertible",
    year: 2022,
    price: 98600,
    mileage: 7400,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: -4,
  },
  {
    ...base,
    id: "sample-11",
    make: "Rivian",
    model: "R1T Adventure",
    bodyType: "Truck",
    year: 2023,
    price: 79900,
    mileage: 12300,
    transmission: "Automatic",
    fuel: "Electric",
    featured: false,
    createdAt: -5,
  },
  {
    ...base,
    id: "sample-12",
    make: "Volkswagen",
    model: "Golf R",
    bodyType: "Hatchback",
    year: 2023,
    price: 45800,
    mileage: 8900,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: -6,
  },
];

export const BODY_TYPES = ["SUV", "Sedan", "Truck", "Coupe", "Convertible", "Hatchback", "Van"];
