import type { Car } from "@/lib/types";

/** Shown on the public site only while Firebase is not configured (local preview). */
const base = {
  color: "",
  description: "",
  status: "available" as const,
  images: [],
  imagePaths: [],
  soldAt: null,
};

export const SAMPLE_CARS: Car[] = [
  {
    ...base,
    id: "sample-1",
    make: "Porsche",
    model: "911 Carrera S",
    bodyType: "Coupe",
    year: 2023,
    price: 142900,
    mileage: 8200,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: true,
    createdAt: 5,
  },
  {
    ...base,
    id: "sample-2",
    make: "Tesla",
    model: "Model S Plaid",
    bodyType: "Sedan",
    year: 2024,
    price: 94990,
    mileage: 3100,
    transmission: "Automatic",
    fuel: "Electric",
    featured: true,
    createdAt: 4,
  },
  {
    ...base,
    id: "sample-3",
    make: "Land Rover",
    model: "Defender 110",
    bodyType: "SUV",
    year: 2022,
    price: 71500,
    mileage: 21400,
    transmission: "Automatic",
    fuel: "Diesel",
    featured: false,
    createdAt: 3,
  },
  {
    ...base,
    id: "sample-4",
    make: "BMW",
    model: "M4 Competition",
    bodyType: "Coupe",
    year: 2023,
    price: 86400,
    mileage: 11900,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: 2,
  },
  {
    ...base,
    id: "sample-5",
    make: "Ford",
    model: "F-150 Lightning",
    bodyType: "Truck",
    year: 2023,
    price: 62800,
    mileage: 14500,
    transmission: "Automatic",
    fuel: "Electric",
    featured: false,
    createdAt: 1,
  },
  {
    ...base,
    id: "sample-6",
    make: "Mercedes-Benz",
    model: "G 550",
    bodyType: "SUV",
    year: 2021,
    price: 148000,
    mileage: 18700,
    transmission: "Automatic",
    fuel: "Gasoline",
    featured: false,
    createdAt: 0,
  },
];

export const BODY_TYPES = ["SUV", "Sedan", "Truck", "Coupe", "Convertible", "Hatchback", "Van"];
